# Generated by Django 3.1.7 on 2021-03-22 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('key', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('pol', 'Politics News'), ('art', 'Art News'), ('tech', 'Technology News'), ('trivia', 'Trivial News')], max_length=20)),
                ('region', models.CharField(choices=[('uk', 'UK News'), ('eu', 'European News'), ('w', 'World News')], default=None, max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
